### ISSUE TITLE
Status Bars - Auto-Select

### ISSUE THREAD

**Issue by TruthNZ** [brittyazel/Ion#4]
Firstly looks like Issues aren't turned on for StatusBars repo.
Either one of the changes you've made, or a change in 7.3 API means the Rep Auto-select isn't working any more - It 's not picking up a rep change and switching to show that rep.

**Comment by brittyazel** [comment]
I'll look into it. Thanks!

**Comment by brittyazel** [comment]
Oh and I didn't turn the issue tracker or wiki on for the other repos because I wanted to keep all that in one place.

**Comment by TruthNZ** [comment]
Fair enough. Perhaps a comment in the readme to report issues here then?

**Comment by brittyazel** [comment]
Good call

**Comment by brittyazel** [comment]
I'm not sure if I can replicate this bug. On mine the auto select is changing my rep bar status to the latest most changed rep source.

**Comment by brittyazel** [comment]
I'll keep digging

**Comment by brittyazel** [comment]
Fixed. It will be in the next version.
